### PR TITLE
[jsk_robot_startup] Fix dependent on linter and support Python3

### PR DESCRIPTION
**Pull request by tkmtnt7000**
This PR fixes format errors from python3 test.
Related to https://github.com/knorth55/jsk_robot/pull/303 [c2c0b04](https://github.com/knorth55/jsk_robot/pull/303/commits/c2c0b04f97a6f233c496ba5c8983751ddd6892da) [8bb35d4](https://github.com/knorth55/jsk_robot/pull/303/commits/8bb35d4814f8196086a761cc4af3acaa28f34f43)

fixes https://github.com/jsk-ros-pkg/jsk_robot/pull/1558

### CODE REVIEW

**Comment by k-okada** [comment]
thank you @tkmtnt7000 
please fix 
```
+++ ./jsk_robot_common/jsk_robot_startup/scripts/smach_to_mail.py	(refactored)
@@ -97,14 +97,14 @@
         status_dict.update({'TIME': datetime.datetime.fromtimestamp(msg.header.stamp.to_sec())})
 
 
-        if ( not self.smach_state_list.has_key(caller_id) ) or self.smach_state_list[caller_id] is None:
+        if ( caller_id not in self.smach_state_list ) or self.smach_state_list[caller_id] is None:
             rospy.logwarn("received {}, but we did not find START node".format(status_dict))
         else:
             self.smach_state_list[caller_id].append(status_dict)
 
         # If we received END/FINISH status, send email, etc...
         if status_str in ["END", "FINISH"]:
-            if ( not self.smach_state_list.has_key(caller_id) ) or self.smach_state_list[caller_id] == None:
+            if ( caller_id not in self.smach_state_list ) or self.smach_state_list[caller_id] == None:
                 rospy.logwarn("received END node, but we did not find START node")
                 rospy.logwarn("failed to send {}".format(status_dict))
             else:
@@ -158,9 +158,9 @@
 
         for x in state_list:
             text = ""
-            if x.has_key('DESCRIPTION'):
RefactoringTool: ./jsk_aero_robot/jsk_aero_startup/test/roslaunch_depends.py
+            if 'DESCRIPTION' in x:
RefactoringTool: ./jsk_baxter_robot/jsk_baxter_startup/jsk_baxter_tools/initialize_baxter.py
                 text = x['DESCRIPTION']
RefactoringTool: ./jsk_fetch_robot/jsk_fetch_diagnosis/node_scripts/check_driver_boards.py
-            if x.has_key('IMAGE') and x['IMAGE']:
RefactoringTool: ./jsk_fetch_robot/jsk_fetch_startup/scripts/latched_topic_republisher.py
+            if 'IMAGE' in x and x['IMAGE']:
                 text += x['IMAGE']
             if len(text) > 1:
                 self.pub_twitter.publish(String(text))
```
too

**Comment by tkmtnt7000** [comment]
Sorry for force-pushing. I fixed format and removed unnecessary modules ([76afca3](https://github.com/k-okada/jsk_robot/pull/70/commits/76afca32e143b0751253c0176447fa458e33c72c)).

**Comment by tkmtnt7000** [comment]
kick test

**Comment by tkmtnt7000** [comment]
meldic test randomly fails around `baxter-moveit`, so I think this doesn't matter in regard to this PR....

**Comment by k-okada** [comment]
@tkmtnt7000 can you see [Re-run jobs} button? If not please let me know. It is too inefficient to close/open PR to fix rondamly failed CI jobs
image

**Comment by tkmtnt7000** [comment]
I cannot see Re-run jobs button.

**Pull request merged**
