### PR TITLE
Add speak volume

### PR DESCRIPTION
**Pull request by Affonso-Gui**
See https://github.com/jsk-ros-pkg/jsk_robot/pull/1535#pullrequestreview-1076782680

### CODE REVIEW

**Comment by k-okada** [comment]
@kochigami are you OK with this change?

**Comment by kochigami** [comment]
Sorry for my late reply.
After https://github.com/Affonso-Gui/jsk_robot/pull/3 is merged, I think this PR can be merged.

**Comment by Affonso-Gui** [comment]
@kochigami Merged the PR.

**Comment by kochigami** [comment]
I think this PR is OK to be merged, but tests (ros melodic, ubuntu:18.04) failed.
When I looked into the test summary, I found both tests failed because `unable to find node [fetch_bringup/controller_reset.py]: fetch_bringup`.
In this case, what should I do...?

**Comment by k-okada** [comment]
fetch_bringup depends on moveit_plannning_interface (https://github.com/ros-planning/moveit/issues/3193), which depends on 
eigenpy (https://github.com/stack-of-tasks/eigenpy/pull/307) that was failing.
Now it seems fixed (https://github.com/ros/rosdistro/pull/34206) and is restarted the failing job

**Pull request merged**
